version: "3.8"

services:
  mc:
    image: itzg/minecraft-server:java17
    container_name: TestMinecraftServer
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      VERSION: 1.20.1
      ONLINE_MODE: "FALSE"
      MEMORY: "4G"
      COPY_CONFIG_DEST: /data
    volumes:
      - ./data:/data
      - ./plugins:/plugins
  db:
    image: mariadb
    container_name: TestDatabase
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mc
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"